spring:
  application:
    name: Authentication-Service

  cloud:
    openfeign:
      multipart:
        enabled: true

  profiles:
    # Let env decide; default to dev if nothing is set
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/backend_user_management?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}


server:
  port: ${SERVER_PORT:8092}

sms:
  base-url: ${SMS_BASE_URL:https://api.mylogin.co.in/api/v2}
  api-key: ${SMS_API_KEY:N9v15Ydho0qL84kMBQGmAMmdE5vfG61D+TF8Nc+X80s=}
  client-id: ${SMS_CLIENT_ID:c5ece875-8559-4e64-805f-c658f0dddc93}
  sender-id: ${SMS_SENDER_ID:MCPNOT}
  numberFormat: CC91        # try CC91 first
  transport: JSON           # if it still fails, try FORM
  dlt:
    template-id: ${SMS_DLT_TEMPLATE_ID:1407175378487206260}
    content: ${SMS_DLT_CONTENT:Your MOC OTP is {#var#}.It is valid for 10 minutes.Do not share this OTP with anyone for security reasons from MOC Connect Private Limited.}
  otp:
    ttl-minutes: ${SMS_OTP_TTL_MINUTES:10}
    digits: ${SMS_OTP_DIGITS:6}
    per-minute-limit: ${SMS_OTP_PER_MINUTE_LIMIT:1}
    per-hour-limit: ${SMS_OTP_PER_HOUR_LIMIT:5}


jwt:
  alg: RS256
  issuer: ${JWT_ISSUER:http://localhost:8092}       # set to your real base URL/host:port
  kid: ${JWT_KID::main-2025-08-16}                  # any stable ID for this key
  audience: ${JWT_AUDIENCE:}
  private-key-pem: |-   # DEV ONLY: embedded PEM. Use env/Secret in prod.
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC0mTzmK0GoD7vN
    73alMwp8Axb1IMMP5UM/UQBNmiIk57KdqPbHvqc7tpfEcWk7fZIKoPSd6Ms+wnOB
    8MoAUT9kU3A0qI4zYQv1K2r6c56heqgL6K37HgEW/akeKmJkKDBAh9qX7t9pNLyP
    RHAM0MRd2lZw+iv6kX3NTH1ZA6IwecUGN0LuTUHZf2WXifYT3MRBbEj9JbvgdCq0
    FA5c4kkTbVF1I6NtHJOxDusqZ7R7FMt3Aj8aMjsjtXhdHQ1m4Md1arWU4Sn/VKSv
    qNzajgxY715WQzCBcyyLs3mXLWdPEuyXu5b0Eb+TWfJg8o8JRUhuTbSvUrqaGpuz
    JzQFlK7xAgMBAAECggEAEtFq0pL29u5Dbpxr8PUbZmZOBJci1tZX8PzdkA3Q+VEj
    6qCvV4s1UsKzwrY3NbSKZ01z37u2PeELdyKMxzFaw8yb7ai96dBMFi0C1dD+r6sf
    tTShYwAH3gpADn1yc3w/4YwmX1whGbhzM2ckA88saZkgFl/tqDYedSoUtOtCLFRp
    nQzSdxnsAQRujJ1cu1MNVQLuKmRnYG2wRP3M1h+sMy4Lp/Q9RMIH8Q+oSybfKkKo
    rIF7eD6q9Bg37FVpRfXiboZi5q6ksieJrtGTMgKMzo8twXupV450cTVX+oHXFI14
    miwEkeTvBjj8dzwGS8EoSW6ZrHHaGkhqlF9ZT3v2bwKBgQDoUTpsXjdFfP9bFCm8
    Ut7tu8AKbj5yTm0gXxBfWC+d45Qm9uNKipWGEYtqMHI5VYFl50GqpAAs2vniAdek
    kJhce8qZK8g16YEcrxbt+6wD9s6FBDK10ohWNG2+WitmG9xAlr3wCJd1fYDn05hC
    KXAxiVv2+opI9ayt+rcMSPMLnwKBgQDHAk8shqMJfZ33cUdYcxsKpaC6mCESS1Qo
    kNSOGbQTKmpzdrn2d1mvZK9VNb8JU/SEs6QqNKYPwUtXTktA745zHqIM9n6jZLlG
    5aM+7fZzrsLCvYu9jDE1b5Q2RHGKf3zIBVdYgrErNUGWpkBesIFiGSz7FCoMdPTN
    rqs8YVs7bwKBgFM9V4ugrnktcml17gZWQx43WXXjTmiyhRNGPJ2NAXK3KkxTxdjd
    kvm4q5Veym6Unoqes76qiI2J4GMEefmy/YSVrl/3egMnKWXXroWS2W2KLzEl8e2I
    A+WvX2sG7+nkLaTO3jt1OJ+WWmu2OyXppxN4vgTefFHsBPVJkfDK6prNAoGAUHqP
    mBsOfb0OD84AozVRXznhyPPSk/pgm1MOkjS0zPdfOzhtNc3IOBTIjvYAPn50KOIY
    5nSKH1703+aqqiT2f3mI4SMhzWPjRVeCb+V9wASRgH10sH+sOsbXsiZ1oCO0S5NV
    Ylbf3PBZiNnMuD465Hf358Wcx5LYmQElAHMCmQMCgYA7Uxt61foGlGtYig/hj3Nr
    +rp8edS0SrPOLX7vH2pqa4ZSdZBbz/PYxQCG4igJozKERE4UrsEYThc7LwMe+7R+
    tZRW/YXMPDwv5Cg37O6uI0nOwZkNlR6zPNi170vsgRvyK0IpBpz+8AT4t5QjBTvw
    m52hs7e3khHwf7S3dYj48Q==
    -----END PRIVATE KEY-----

# optional rotation support (publish old public key alongside the new one)
  previous-kid: ${JWT_PREV_KID:}
  previous-public-pem: |-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJk85itBqA+7ze92pTMK
    fAMW9SDDD+VDP1EATZoiJOeynaj2x76nO7aXxHFpO32SCqD0nejLPsJzgfDKAFE/
    ZFNwNKiOM2EL9Stq+nOeoXqoC+it+x4BFv2pHipiZCgwQIfal+7faTS8j0RwDNDE
    XdpWcPor+pF9zUx9WQOiMHnFBjdC7k1B2X9ll4n2E9zEQWxI/SW74HQqtBQOXOJJ
    E21RdSOjbRyTsQ7rKme0exTLdwI/GjI7I7V4XR0NZuDHdWq1lOEp/1Skr6jc2o4M
    WO9eVkMwgXMsi7N5ly1nTxLsl7uW9BG/k1nyYPKPCUVIbk20r1K6mhqbsyc0BZSu
    8QIDAQAB
    -----END PUBLIC KEY-----
  access-ttl-min: ${JWT_ACCESS_TTL_MIN:50000}
  refresh-ttl-days: ${JWT_REFRESH_TTL_DAYS:180}

media:
  bucket: ${MEDIA_BUCKET:moc-prod}   # default "moc-prod", override via env var MEDIA_BUCKET

# (recommended—where to call RTC)
rtc:
  base-url: ${RTC_BASE_URL:http://localhost:8091}

# optional, nice-to-have knobs used by AvatarService
avatar:
  max-size-bytes: ${AVATAR_MAX_SIZE_BYTES:5242880}      # 5 MB
  put-url-ttl-seconds: ${AVATAR_PUT_TTL_SECONDS:600}
  get-url-ttl-seconds: ${AVATAR_GET_TTL_SECONDS:600}


# Keep this custom and read it in a @ConfigurationProperties or @Value
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:19006,http://localhost:8081,capacitor://localhost}

app:
  clock:
    zone: Asia/Kolkata
  issuer: ${JWT_ISSUER:http://localhost:8092}
